version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mortgage-backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/mortgage.db
      - PORT=8080
      # - FRONTEND_URL=http://localhost:3000
      # - IS_PRODUCTION=true
    restart: unless-stopped
